"""Add phone field to users

Revision ID: 294e9d8f4d37
Revises: e95682f515ff
Create Date: 2026-01-07 01:22:33.620410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294e9d8f4d37'
down_revision = 'e95682f515ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_medical', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_medical')
    # ### end Alembic commands ###
